version: '3.4'

services:
  inventory.api:
    container_name: ms-test.inventory.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "Server=ms-test.db;Database=InventoryDb;User Id=InventoryUser;Password=SwN12345678;"            
    ports:
        - "8001:80"
  order.api:
    container_name: ms-test.ordering.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development" 
        - "ApiSettings:InventoryUrl=ms-test.inventory.api"
    depends_on:
        - ms-test.inventory.api
    ports:
        - "8002:80"

