version: '3.4'

services:
  inventory.api:
    container_name: ms-test.inventory.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings__InventoryConnectionString=Server=msdb;Database=InventoryDb;User Id=sa;Password=AlEx12345678"  
        - "ElasticConfiguration__URI=http://elasticsearch:9200"
    depends_on:
        - msdb
    ports:
        - "8501:80"
    networks:
        - ms_network
  order.api:
    container_name: ms-test.order.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ApiSettings__InventoryUrl=http://inventory.api"
        - "ElasticConfiguration__URI=http://elasticsearch:9200"
    ports:
        - "8502:80"
    networks:
        - ms_network
  msdb:
    container_name: msdb
    environment:
        SA_PASSWORD: "AlEx12345678"
        ACCEPT_EULA: "Y"
    volumes: 
        - C:\Dev Else\BACKUP\KEEP:/var/opt/mssql/backups
        - ms_mssqluser:/var/opt/sqlserver
        - ms_mssqlsystem:/var/opt/mssql
    restart: always
    ports:
        - "8030:1433"
    networks:
         - ms_network

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data   
    networks:
        - ms_network

  kibana:
    container_name: kibana
    environment:        
        - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601" 
    networks:
        - ms_network

networks:
    ms_network:
        driver: bridge

volumes:
  ms_mssqluser:
    driver: local
  ms_mssqlsystem:
    driver: local
  elasticsearch-data: